
export const INSTAGRAM_URL = "https://instagram.com/eusoufabriciomenezes";

export const DESTINATIONS_LIST = [
  "Paris, França", "Santorini, Grécia", "Dubai, Emirados Árabes", "Tóquio, Japão",
  "Machu Picchu, Peru", "Rio de Janeiro, Brasil", "Nova York, EUA", "Roma, Itália",
  "Maldivas", "Cairo, Egito", "Sydney, Austrália", "Londres, Reino Unido",
  "Capadócia, Turquia", "Queenstown, Nova Zelândia", "Veneza, Itália", "Praga, República Tcheca",
  "Cidade do Cabo, África do Sul", "Kyoto, Japão", "Amsterdã, Holanda", "Barcelona, Espanha",
  "Bali, Indonésia", "Berlim, Alemanha", "Moscou, Rússia", "Seul, Coreia do Sul",
  "Istambul, Turquia", "Pequim, China", "Bangkok, Tailândia", "Havana, Cuba",
  "Dubai, Emirados Árabes Unidos", "São Francisco, EUA", "Edimburgo, Escócia", "Hamburgo, Alemanha",
  "Oslo, Noruega", "Lisboa, Portugal", "Budapeste, Hungria", "Buenos Aires, Argentina",
  "Vancouver, Canadá", "Helsinque, Finlândia", "Dublin, Irlanda", "Mumbai, Índia",
  "Marrakech, Marrocos", "Cartagena, Colômbia", "Santiago, Chile", "Sydney, Austrália",
  "Tóquio, Japão", "Atenas, Grécia", "Punta Cana, República Dominicana", "Cancún, México",
  "Bangkok, Tailândia", "Cingapura", "Buenos Aires, Argentina", "Cidade do Cabo, África do Sul",
  "Toronto, Canadá", "Zurique, Suíça", "Viena, Áustria", "Hanoi, Vietnã",
  "Phuket, Tailândia", "Miami, EUA", "São Paulo, Brasil", "Cidade do México, México",
  "Cairo, Egito", "Doha, Catar", "Abu Dhabi, Emirados Árabes Unidos", "Lisboa, Portugal",
  "Munique, Alemanha", "Varsóvia, Polônia", "Bucareste, Romênia", "Istambul, Turquia",
  "Seul, Coreia do Sul", "Taipei, Taiwan", "Mumbai, Índia", "Bombaim, Índia",
  "Jacarta, Indonésia", "Manila, Filipinas", "Kuala Lumpur, Malásia", "Pequim, China",
  "Shanghai, China", "Ho Chi Minh City, Vietnã", "Dubai, Emirados Árabes Unidos", "Jerusalém, Israel",
  "Tel Aviv, Israel", "Berlim, Alemanha", "Amsterdã, Holanda", "Bruxelas, Bélgica",
  "Genebra, Suíça", "Florença, Itália", "Sevilha, Espanha", "Porto, Portugal",
  "Dublin, Irlanda", "Estocolmo, Suécia", "Copenhague, Dinamarca", "Helsinque, Finlândia",
  "Oslo, Noruega", "Reikjavik, Islândia", "Vancouver, Canadá", "Montreal, Canadá",
  "Quebec City, Canadá", "Boston, EUA", "Chicago, EUA", "Los Angeles, EUA",
  "Washington D.C., EUA", "Nova Orleans, EUA", "Orlando, EUA", "Las Vegas, EUA",
  "San Diego, EUA", "Denver, EUA", "Seattle, EUA", "Miami, EUA",
  "Honolulu, EUA", "São Francisco, EUA", "Santiago, Chile", "Bogotá, Colômbia",
  "Lima, Peru", "Quito, Equador", "Medellín, Colômbia", "Cartagena, Colômbia",
  "Punta Cana, República Dominicana", "Havana, Cuba", "San Juan, Porto Rico", "Kingston, Jamaica",
  "Nassau, Bahamas", "Cidade do Panamá, Panamá", "San José, Costa Rica", "Cidade da Guatemala, Guatemala",
  "Belize City, Belize", "Cancún, México", "Cidade do México, México", "Puerto Vallarta, México",
  "Acapulco, México", "Playa del Carmen, México", "Tijuana, México", "Guadalajara, México",
  "Monterrey, México", "Quebec, Canadá", "Ottawa, Canadá", "Calgary, Canadá",
  "Edmonton, Canadá", "Winnipeg, Canadá", "Saskatoon, Canadá", "Victoria, Canadá",
  "Halifax, Canadá", "St. John's, Canadá", "Paris, França", "Londres, Reino Unido",
  "Roma, Itália", "Madrid, Espanha", "Berlim, Alemanha", "Amsterdã, Holanda",
  "Bruxelas, Bélgica", "Viena, Áustria", "Praga, República Tcheca", "Budapeste, Hungria",
  "Varsóvia, Polônia", "Lisboa, Portugal", "Dublin, Irlanda", "Edimburgo, Escócia",
  "Copenhague, Dinamarca", "Estocolmo, Suécia", "Oslo, Noruega", "Helsinque, Finlândia",
  "Reikjavik, Islândia", "Atenas, Grécia", "Istambul, Turquia", "Moscou, Rússia",
  "São Petersburgo, Rússia", "Kiev, Ucrânia", "Varsóvia, Polônia", "Cracóvia, Polônia",
  "Bucareste, Romênia", "Sofia, Bulgária", "Belgrado, Sérvia", "Zagreb, Croácia",
  "Ljubljana, Eslovênia", "Sarajevo, Bósnia e Herzegovina", "Tirana, Albânia", "Skopje, Macedônia do Norte",
  "Pristina, Kosovo", "Valletta, Malta", "Nicósia, Chipre", "Tel Aviv, Israel",
  "Jerusalém, Israel", "Amã, Jordânia", "Beirute, Líbano", "Cairo, Egito",
  "Casablanca, Marrocos", "Túnis, Tunísia", "Argel, Argélia", "Dakar, Senegal",
  "Acra, Gana", "Lagos, Nigéria", "Nairóbi, Quênia", "Cidade do Cabo, África do Sul",
  "Joanesburgo, África do Sul", "Pretória, África do Sul", "Port Louis, Maurícia", "Antananarivo, Madagascar",
  "Abu Dhabi, Emirados Árabes Unidos", "Doha, Catar", "Manama, Bahrein", "Kuwait City, Kuwait",
  "Mascate, Omã", "Riade, Arábia Saudita", "Teerã, Irã", "Bagdá, Iraque",
  "Cabul, Afeganistão", "Islamabad, Paquistão", "Karachi, Paquistão", "Lahore, Paquistão",
  "Nova Delhi, Índia", "Mumbai, Índia", "Bangalore, Índia", "Chennai, Índia",
  "Calcutá, Índia", "Dhaka, Bangladesh", "Katmandu, Nepal", "Thimphu, Butão",
  "Colombo, Sri Lanka", "Male, Maldivas", "Bangkok, Tailândia", "Chiang Mai, Tailândia",
  "Hanói, Vietnã", "Ho Chi Minh City, Vietnã", "Siem Reap, Camboja", "Vientiane, Laos",
  "Yangon, Mianmar", "Kuala Lumpur, Malásia", "Cingapura", "Jacarta, Indonésia",
  "Bali, Indonésia", "Manila, Filipinas", "Seul, Coreia do Sul", "Tóquio, Japão",
  "Kyoto, Japão", "Osaka, Japão", "Pequim, China", "Shanghai, China",
  "Hong Kong, China", "Taipei, Taiwan", "Ulaanbaatar, Mongólia", "Sydney, Austrália",
  "Melbourne, Austrália", "Brisbane, Austrália", "Perth, Austrália", "Adelaide, Austrália",
  "Canberra, Austrália", "Queenstown, Nova Zelândia", "Auckland, Nova Zelândia", "Wellington, Nova Zelândia",
  "Suva, Fiji", "Papeete, Polinésia Francesa", "Honolulu, EUA", "Anchorage, EUA",
  "Juneau, EUA", "Vancouver, Canadá", "Edmonton, Canadá", "Calgary, Canadá",
  "Winnipeg, Canadá", "Toronto, Canadá", "Ottawa, Canadá", "Montreal, Canadá",
  "Quebec City, Canadá", "Halifax, Canadá", "St. John's, Canadá", "Cidade do Cabo, África do Sul",
  "Johanesburgo, África do Sul", "Pretória, África do Sul", "Durban, África do Sul", "Bloemfontein, África do Sul",
  "Windhoek, Namíbia", "Gaborone, Botsuana", "Lusaca, Zâmbia", "Harare, Zimbábue",
  "Maputo, Moçambique", "Antananarivo, Madagascar", "Port Louis, Maurícia", "Victoria, Seychelles",
  "Túnis, Tunísia", "Argel, Argélia", "Trípoli, Líbia", "Cartum, Sudão",
  "Adis Abeba, Etiópia", "Nairóbi, Quênia", "Dar es Salaam, Tanzânia", "Campala, Uganda",
  "Kigali, Ruanda", "Bujumbura, Burundi", "Kinshasa, República Democrática do Congo", "Brazzaville, República do Congo",
  "Luanda, Angola", "Dakar, Senegal", "Acra, Gana", "Abidjan, Costa do Marfim",
  "Lagos, Nigéria", "Niamey, Níger", "Bamako, Mali", "Ouagadougou, Burkina Faso",
  "Freetown, Serra Leoa", "Monróvia, Libéria", "Bissau, Guiné-Bissau", "Conakry, Guiné",
  "Nouakchott, Mauritânia", "Praia, Cabo Verde", "São Tomé, São Tomé e Príncipe"
];
